Watching for file changes with StatReloader
/Users/denisburguto/test2django/test_project/testapp/views.py changed, reloading.
Watching for file changes with StatReloader
Not Found: /
"GET / HTTP/1.1" 404 2172
/Users/denisburguto/test2django/test_project/test_project/urls.py changed, reloading.
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 13
"GET / HTTP/1.1" 200 13
"GET /admin/login/?next=/admin/ HTTP/1.1" 200 4181
"GET /static/admin/css/base.css HTTP/1.1" 304 0
"GET /static/admin/css/dark_mode.css HTTP/1.1" 304 0
"GET /static/admin/js/theme.js HTTP/1.1" 304 0
"GET /static/admin/css/nav_sidebar.css HTTP/1.1" 304 0
"GET /static/admin/js/nav_sidebar.js HTTP/1.1" 304 0
"GET /static/admin/css/login.css HTTP/1.1" 304 0
"GET /static/admin/css/responsive.css HTTP/1.1" 304 0
"GET /about/ HTTP/1.1" 200 8
/Users/denisburguto/test2django/test_project/test_project/settings.py changed, reloading.
Watching for file changes with StatReloader
/Users/denisburguto/test2django/test_project/test_project/settings.py changed, reloading.
INFO 2024-03-25 16:37:33,121 autoreload 4766 8444754624 Watching for file changes with StatReloader
INFO 2024-03-25 16:37:34,399 basehttp 4766 6169931776 "GET / HTTP/1.1" 200 13
INFO 2024-03-25 16:39:39,864 basehttp 4766 6169931776 "GET / HTTP/1.1" 200 13
WARNING 2024-03-25 16:40:25,816 log 4766 6169931776 Not Found: /about/k
WARNING 2024-03-25 16:40:25,817 basehttp 4766 6169931776 "GET /about/k HTTP/1.1" 404 2432
INFO 2024-03-28 05:34:00,482 autoreload 7315 8444754624 Watching for file changes with StatReloader
INFO 2024-03-28 05:34:01,838 basehttp 7315 6123745280 "GET / HTTP/1.1" 200 13
INFO 2024-03-28 05:37:36,208 autoreload 7315 8444754624 /Users/denisburguto/test2django/test_project/testapp/views.py changed, reloading.
INFO 2024-03-28 05:37:36,474 autoreload 7351 8444754624 Watching for file changes with StatReloader
INFO 2024-03-28 05:37:37,954 basehttp 7351 6130954240 "GET / HTTP/1.1" 200 13
INFO 2024-03-28 05:37:44,720 basehttp 7351 6130954240 "GET / HTTP/1.1" 200 13
INFO 2024-03-28 05:37:45,918 basehttp 7351 6130954240 "GET /about/ HTTP/1.1" 200 27
INFO 2024-03-28 05:38:23,246 autoreload 7351 8444754624 /Users/denisburguto/test2django/test_project/test_project/settings.py changed, reloading.
INFO 2024-03-28 05:40:03,289 autoreload 7383 8444754624 Watching for file changes with StatReloader
INFO 2024-03-28 05:40:04,644 basehttp 7383 6127022080 "GET / HTTP/1.1" 200 13
INFO 2024-03-28 05:40:14,363 basehttp 7383 6127022080 "GET / HTTP/1.1" 200 13
INFO 2024-03-28 05:40:15,904 basehttp 7383 6127022080 "GET /about/ HTTP/1.1" 200 27
INFO 2024-03-28 05:41:10,394 autoreload 7383 8444754624 /Users/denisburguto/test2django/test_project/test_project/settings.py changed, reloading.
INFO 2024-03-28 05:41:10,604 autoreload 7402 8444754624 Watching for file changes with StatReloader
INFO 2024-03-28 05:41:17,769 basehttp 7402 6159118336 "GET / HTTP/1.1" 200 13
INFO 2024-03-28 05:43:31,992 autoreload 7402 8444754624 /Users/denisburguto/test2django/test_project/test_project/settings.py changed, reloading.
INFO 2024-03-28 05:43:32,297 autoreload 7435 8444754624 Watching for file changes with StatReloader
INFO 2024-03-28 05:43:33,538 basehttp 7435 6166622208 "GET / HTTP/1.1" 200 13
INFO 2024-03-28 05:43:41,691 basehttp 7435 6166622208 "GET / HTTP/1.1" 200 13
INFO 2024-03-28 05:43:49,182 basehttp 7435 6166622208 "GET / HTTP/1.1" 200 13
INFO 2024-03-28 05:43:52,004 basehttp 7435 6166622208 "GET / HTTP/1.1" 200 13
INFO 2024-03-28 05:43:52,610 basehttp 7435 6166622208 "GET /about/ HTTP/1.1" 200 27
INFO 2024-03-28 05:44:24,290 autoreload 7435 8444754624 /Users/denisburguto/test2django/test_project/test_project/settings.py changed, reloading.
INFO 2024-03-28 05:44:24,562 autoreload 7447 8444754624 Watching for file changes with StatReloader
INFO 2024-03-28 05:47:43,007 autoreload 7447 8444754624 /Users/denisburguto/test2django/test_project/testapp/views.py changed, reloading.
INFO 2024-03-28 05:47:43,305 autoreload 7486 8444754624 Watching for file changes with StatReloader
INFO 2024-03-28 05:47:44,626 basehttp 7486 6163394560 "GET / HTTP/1.1" 200 13
INFO 2024-03-28 05:48:23,032 autoreload 7486 8444754624 /Users/denisburguto/test2django/test_project/testapp/views.py changed, reloading.
INFO 2024-03-28 05:48:23,219 autoreload 7500 8444754624 Watching for file changes with StatReloader
ERROR 2024-03-28 05:48:24,244 log 7500 6205091840 Internal Server Error: /
Traceback (most recent call last):
  File "/Users/denisburguto/Library/Python/3.9/lib/python/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/denisburguto/Library/Python/3.9/lib/python/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/denisburguto/test2django/test_project/testapp/views.py", line 9, in index
    logger.log('we')
TypeError: log() missing 1 required positional argument: 'msg'
ERROR 2024-03-28 05:48:24,245 basehttp 7500 6205091840 "GET / HTTP/1.1" 500 64731
INFO 2024-03-28 05:48:48,615 autoreload 7500 8444754624 /Users/denisburguto/test2django/test_project/testapp/views.py changed, reloading.
INFO 2024-03-28 05:48:48,803 autoreload 7510 8444754624 Watching for file changes with StatReloader
ERROR 2024-03-28 05:48:49,827 log 7510 6200799232 Internal Server Error: /
Traceback (most recent call last):
  File "/Users/denisburguto/Library/Python/3.9/lib/python/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/denisburguto/Library/Python/3.9/lib/python/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/denisburguto/test2django/test_project/testapp/views.py", line 9, in index
    logger.log(msg='e')
TypeError: log() missing 1 required positional argument: 'level'
ERROR 2024-03-28 05:48:49,828 basehttp 7510 6200799232 "GET / HTTP/1.1" 500 64745
INFO 2024-03-28 05:49:37,565 autoreload 7510 8444754624 /Users/denisburguto/test2django/test_project/testapp/views.py changed, reloading.
INFO 2024-03-28 05:49:37,752 autoreload 7526 8444754624 Watching for file changes with StatReloader
ERROR 2024-03-28 05:49:39,021 log 7526 6203781120 Internal Server Error: /
Traceback (most recent call last):
  File "/Users/denisburguto/Library/Python/3.9/lib/python/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/denisburguto/Library/Python/3.9/lib/python/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/denisburguto/test2django/test_project/testapp/views.py", line 9, in index
    logger.log(msg='e', level="info")
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/logging/__init__.py", line 1508, in log
    raise TypeError("level must be an integer")
TypeError: level must be an integer
ERROR 2024-03-28 05:49:39,022 basehttp 7526 6203781120 "GET / HTTP/1.1" 500 68958
INFO 2024-03-28 05:49:51,077 autoreload 7526 8444754624 /Users/denisburguto/test2django/test_project/testapp/views.py changed, reloading.
INFO 2024-03-28 05:49:51,266 autoreload 7533 8444754624 Watching for file changes with StatReloader
INFO 2024-03-28 05:49:52,418 basehttp 7533 6135427072 "GET / HTTP/1.1" 200 13
INFO 2024-03-28 05:50:47,267 autoreload 7533 8444754624 /Users/denisburguto/test2django/test_project/testapp/views.py changed, reloading.
INFO 2024-03-28 05:50:47,458 autoreload 7542 8444754624 Watching for file changes with StatReloader
INFO 2024-03-28 05:54:14,946 autoreload 7542 8444754624 /Users/denisburguto/test2django/test_project/test_project/settings.py changed, reloading.
INFO 2024-03-28 05:54:15,288 autoreload 7650 8444754624 Watching for file changes with StatReloader
INFO 2024-03-28 05:54:16,312 basehttp 7650 6201683968 "GET / HTTP/1.1" 200 13
INFO 2024-03-28 05:55:09,088 autoreload 7650 8444754624 /Users/denisburguto/test2django/test_project/testapp/views.py changed, reloading.
INFO 2024-03-28 05:55:09,282 autoreload 7667 8444754624 Watching for file changes with StatReloader
INFO 2024-03-28 05:55:10,753 views 7667 6167064576 Index page accessed
INFO 2024-03-28 05:55:10,754 basehttp 7667 6167064576 "GET / HTTP/1.1" 200 13
INFO 2024-03-28 06:03:40,541 autoreload 7837 8444754624 Watching for file changes with StatReloader
INFO 2024-03-28 06:03:42,369 views 7837 6203617280 Index page accessed
INFO 2024-03-28 06:03:42,370 basehttp 7837 6203617280 "GET / HTTP/1.1" 200 13
INFO 2024-03-30 04:08:44,982 autoreload 11036 8444754624 Watching for file changes with StatReloader
INFO 2024-03-30 04:09:08,020 autoreload 11083 8444754624 Watching for file changes with StatReloader
INFO 2024-03-30 04:09:13,850 views 11083 6133035008 Index page accessed
INFO 2024-03-30 04:09:13,851 basehttp 11083 6133035008 "GET / HTTP/1.1" 200 13
INFO 2024-03-30 04:14:59,071 autoreload 11154 8444754624 Watching for file changes with StatReloader
INFO 2024-03-30 06:49:26,183 autoreload 14734 8444754624 Watching for file changes with StatReloader
INFO 2024-03-30 06:51:40,712 autoreload 14927 8444754624 Watching for file changes with StatReloader
INFO 2024-03-30 07:28:29,988 autoreload 14927 8444754624 /Users/denisburguto/test2django/test_project/testapp2/models.py changed, reloading.
INFO 2024-03-30 07:28:30,277 autoreload 15412 8444754624 Watching for file changes with StatReloader
INFO 2024-04-02 05:58:26,149 autoreload 25731 8444820160 Watching for file changes with StatReloader
INFO 2024-04-02 05:59:11,276 autoreload 25790 8444820160 Watching for file changes with StatReloader
INFO 2024-04-02 05:59:35,352 autoreload 25821 8444820160 Watching for file changes with StatReloader
INFO 2024-04-02 06:00:32,946 autoreload 25879 8444820160 Watching for file changes with StatReloader
INFO 2024-04-02 06:01:21,577 autoreload 25962 8444820160 Watching for file changes with StatReloader
INFO 2024-04-02 13:57:26,555 autoreload 20380 8444754624 Watching for file changes with StatReloader
INFO 2024-04-02 13:57:52,931 autoreload 20380 8444754624 /Users/denisburguto/test2django/test_project/test_project/urls.py changed, reloading.
INFO 2024-04-02 13:57:53,169 autoreload 20388 8444754624 Watching for file changes with StatReloader
INFO 2024-04-02 13:58:02,303 autoreload 20388 8444754624 /Users/denisburguto/test2django/test_project/test_project/urls.py changed, reloading.
INFO 2024-04-02 13:58:02,520 autoreload 20394 8444754624 Watching for file changes with StatReloader
INFO 2024-04-02 13:59:04,426 autoreload 20394 8444754624 /Users/denisburguto/test2django/test_project/testapp3/views.py changed, reloading.
INFO 2024-04-02 13:59:04,680 autoreload 20409 8444754624 Watching for file changes with StatReloader
INFO 2024-04-02 13:59:10,850 autoreload 20409 8444754624 /Users/denisburguto/test2django/test_project/testapp3/urls.py changed, reloading.
INFO 2024-04-02 13:59:11,040 autoreload 20418 8444754624 Watching for file changes with StatReloader
INFO 2024-04-02 14:00:03,212 autoreload 20451 8444754624 Watching for file changes with StatReloader
INFO 2024-04-02 14:00:19,377 autoreload 20490 8444754624 Watching for file changes with StatReloader
INFO 2024-04-02 14:00:20,946 views 20490 6155235328 Index page accessed
INFO 2024-04-02 14:00:20,946 basehttp 20490 6155235328 "GET / HTTP/1.1" 200 13
WARNING 2024-04-02 14:00:20,989 log 20490 6172061696 Not Found: /apple-touch-icon-precomposed.png
WARNING 2024-04-02 14:00:20,989 basehttp 20490 6172061696 "GET /apple-touch-icon-precomposed.png HTTP/1.1" 404 2613
WARNING 2024-04-02 14:00:20,992 log 20490 6172061696 Not Found: /apple-touch-icon.png
WARNING 2024-04-02 14:00:20,992 basehttp 20490 6172061696 "GET /apple-touch-icon.png HTTP/1.1" 404 2577
WARNING 2024-04-02 14:00:21,022 log 20490 6155235328 Not Found: /favicon.ico
WARNING 2024-04-02 14:00:21,022 basehttp 20490 6155235328 "GET /favicon.ico HTTP/1.1" 404 2550
INFO 2024-04-02 14:00:42,319 basehttp 20490 6155235328 "GET /three/hello HTTP/1.1" 301 0
INFO 2024-04-02 14:00:42,335 basehttp 20490 6155235328 "GET /three/hello/ HTTP/1.1" 200 26
INFO 2024-04-02 14:01:07,187 basehttp 20490 6155235328 "GET /three/hello_class HTTP/1.1" 301 0
ERROR 2024-04-02 14:01:07,228 log 20490 6155235328 Internal Server Error: /three/hello_class/
Traceback (most recent call last):
  File "/Users/denisburguto/Library/Python/3.9/lib/python/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/denisburguto/Library/Python/3.9/lib/python/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
TypeError: as_view() takes 1 positional argument but 2 were given
ERROR 2024-04-02 14:01:07,229 basehttp 20490 6155235328 "GET /three/hello_class/ HTTP/1.1" 500 62088
INFO 2024-04-02 14:01:19,665 autoreload 20490 8444754624 /Users/denisburguto/test2django/test_project/testapp3/urls.py changed, reloading.
INFO 2024-04-02 14:01:19,934 autoreload 20502 8444754624 Watching for file changes with StatReloader
INFO 2024-04-02 14:01:23,068 basehttp 20502 6194229248 "GET /three/hello_class/ HTTP/1.1" 200 23
INFO 2024-04-02 14:05:23,164 views 20502 6194229248 Index page accessed
INFO 2024-04-02 14:05:23,165 basehttp 20502 6194229248 "GET / HTTP/1.1" 200 13
INFO 2024-04-02 14:05:32,539 views 20502 6194229248 Index page accessed
INFO 2024-04-02 14:05:32,540 basehttp 20502 6194229248 "GET / HTTP/1.1" 200 13
INFO 2024-04-02 14:05:34,022 basehttp 20502 6194229248 "GET /three/hello_class/ HTTP/1.1" 200 23
INFO 2024-04-02 14:05:41,516 basehttp 20502 6194229248 "GET /three/hello_class/ HTTP/1.1" 200 23
WARNING 2024-04-02 14:05:42,798 log 20502 6194229248 Not Found: /three
WARNING 2024-04-02 14:05:42,798 basehttp 20502 6194229248 "GET /three HTTP/1.1" 404 2532
INFO 2024-04-02 14:05:51,164 basehttp 20502 6194229248 "GET /three/hello_class/ HTTP/1.1" 200 23
INFO 2024-04-02 14:05:55,546 basehttp 20502 6194229248 "GET /three/hello_class/ HTTP/1.1" 200 23
WARNING 2024-04-02 14:05:57,166 log 20502 6194229248 Not Found: /three/
WARNING 2024-04-02 14:05:57,166 basehttp 20502 6194229248 "GET /three/ HTTP/1.1" 404 2786
INFO 2024-04-02 14:15:36,956 autoreload 20502 8444754624 /Users/denisburguto/test2django/test_project/testapp3/views.py changed, reloading.
INFO 2024-04-02 14:15:37,265 autoreload 20596 8444754624 Watching for file changes with StatReloader
INFO 2024-04-02 14:19:49,955 autoreload 20596 8444754624 /Users/denisburguto/test2django/test_project/testapp3/views.py changed, reloading.
INFO 2024-04-02 14:19:50,228 autoreload 20634 8444754624 Watching for file changes with StatReloader
INFO 2024-04-02 14:20:48,077 autoreload 20634 8444754624 /Users/denisburguto/test2django/test_project/testapp3/urls.py changed, reloading.
INFO 2024-04-02 14:20:48,264 autoreload 20660 8444754624 Watching for file changes with StatReloader
INFO 2024-04-02 14:20:50,044 views 20660 6132051968 Index page accessed
INFO 2024-04-02 14:20:50,044 basehttp 20660 6132051968 "GET / HTTP/1.1" 200 13
INFO 2024-04-02 14:21:05,566 views 20660 6132051968 Index page accessed
INFO 2024-04-02 14:21:05,566 basehttp 20660 6132051968 "GET / HTTP/1.1" 200 13
WARNING 2024-04-02 14:21:29,297 log 20660 6132051968 Not Found: /three/posts
WARNING 2024-04-02 14:21:29,298 basehttp 20660 6132051968 "GET /three/posts HTTP/1.1" 404 3440
INFO 2024-04-02 14:21:37,521 basehttp 20660 6132051968 "GET /three/posts/2022 HTTP/1.1" 301 0
INFO 2024-04-02 14:21:37,539 basehttp 20660 6132051968 "GET /three/posts/2022/ HTTP/1.1" 200 19
INFO 2024-04-02 14:21:42,230 basehttp 20660 6132051968 "GET /three/posts/2022/4 HTTP/1.1" 301 0
INFO 2024-04-02 14:21:42,249 basehttp 20660 6132051968 "GET /three/posts/2022/4/ HTTP/1.1" 200 21
INFO 2024-04-02 14:21:50,769 basehttp 20660 6132051968 "GET /three/posts/2022/4/java HTTP/1.1" 301 0
INFO 2024-04-02 14:21:50,786 basehttp 20660 6132051968 "GET /three/posts/2022/4/java/ HTTP/1.1" 200 364
INFO 2024-04-02 14:22:48,576 autoreload 20660 8444754624 /Users/denisburguto/test2django/test_project/testapp3/views.py changed, reloading.
INFO 2024-04-02 14:22:48,841 autoreload 20674 8444754624 Watching for file changes with StatReloader
INFO 2024-04-02 14:22:53,639 basehttp 20674 6167162880 "GET /three/posts/2022/4/java/ HTTP/1.1" 200 856
INFO 2024-04-02 14:23:11,393 autoreload 20674 8444754624 /Users/denisburguto/test2django/test_project/testapp3/views.py changed, reloading.
INFO 2024-04-02 14:23:11,575 autoreload 20682 8444754624 Watching for file changes with StatReloader
INFO 2024-04-02 14:23:16,095 basehttp 20682 6200651776 "GET /three/posts/2022/4/java/ HTTP/1.1" 200 364
INFO 2024-04-02 14:23:55,223 basehttp 20682 6217478144 "GET /three/posts/2022/4/java/ HTTP/1.1" 200 364
WARNING 2024-04-02 14:23:55,282 log 20682 6217478144 Not Found: /favicon.ico
WARNING 2024-04-02 14:23:55,282 basehttp 20682 6217478144 "GET /favicon.ico HTTP/1.1" 404 2550
INFO 2024-04-02 14:33:45,062 autoreload 20682 8444754624 /Users/denisburguto/test2django/test_project/testapp3/views.py changed, reloading.
INFO 2024-04-02 14:33:45,344 autoreload 20868 8444754624 Watching for file changes with StatReloader
INFO 2024-04-02 14:33:51,202 basehttp 20868 6157430784 "GET /three/posts/2022/4/java/ HTTP/1.1" 200 364
INFO 2024-04-02 14:33:52,602 basehttp 20868 6157430784 "GET /three/posts/2022/ HTTP/1.1" 200 19
INFO 2024-04-02 14:33:54,760 basehttp 20868 6157430784 "GET /three/posts/2022/ HTTP/1.1" 200 19
INFO 2024-04-02 14:33:55,211 basehttp 20868 6157430784 "GET /three/hello_class/ HTTP/1.1" 200 23
ERROR 2024-04-02 14:33:58,668 log 20868 6157430784 Internal Server Error: /three/my/den
Traceback (most recent call last):
  File "/Users/denisburguto/Library/Python/3.9/lib/python/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/denisburguto/Library/Python/3.9/lib/python/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/denisburguto/test2django/test_project/testapp3/views.py", line 43, in my_view
    return render(request, "testapp3/my_temp.html", context)
  File "/Users/denisburguto/Library/Python/3.9/lib/python/site-packages/django/shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Users/denisburguto/Library/Python/3.9/lib/python/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/Users/denisburguto/Library/Python/3.9/lib/python/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: testapp3/my_temp.html
ERROR 2024-04-02 14:33:58,670 basehttp 20868 6157430784 "GET /three/my/den HTTP/1.1" 500 79128
ERROR 2024-04-02 14:37:32,395 log 20868 6157430784 Internal Server Error: /three/my/den
Traceback (most recent call last):
  File "/Users/denisburguto/Library/Python/3.9/lib/python/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/denisburguto/Library/Python/3.9/lib/python/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/denisburguto/test2django/test_project/testapp3/views.py", line 43, in my_view
    return render(request, "testapp3/my_temp.html", context)
  File "/Users/denisburguto/Library/Python/3.9/lib/python/site-packages/django/shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Users/denisburguto/Library/Python/3.9/lib/python/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/Users/denisburguto/Library/Python/3.9/lib/python/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: testapp3/my_temp.html
ERROR 2024-04-02 14:37:32,396 basehttp 20868 6157430784 "GET /three/my/den HTTP/1.1" 500 79128
INFO 2024-04-02 14:37:40,545 autoreload 20915 8444754624 Watching for file changes with StatReloader
ERROR 2024-04-02 14:37:43,888 log 20915 6164508672 Internal Server Error: /three/my/den
Traceback (most recent call last):
  File "/Users/denisburguto/Library/Python/3.9/lib/python/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/denisburguto/Library/Python/3.9/lib/python/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/denisburguto/test2django/test_project/testapp3/views.py", line 43, in my_view
    return render(request, "testapp3/my_temp.html", context)
  File "/Users/denisburguto/Library/Python/3.9/lib/python/site-packages/django/shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Users/denisburguto/Library/Python/3.9/lib/python/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/Users/denisburguto/Library/Python/3.9/lib/python/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: testapp3/my_temp.html
ERROR 2024-04-02 14:37:43,892 basehttp 20915 6164508672 "GET /three/my/den HTTP/1.1" 500 79128
ERROR 2024-04-02 14:37:48,171 log 20915 6164508672 Internal Server Error: /three/my/den
Traceback (most recent call last):
  File "/Users/denisburguto/Library/Python/3.9/lib/python/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/denisburguto/Library/Python/3.9/lib/python/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/denisburguto/test2django/test_project/testapp3/views.py", line 43, in my_view
    return render(request, "testapp3/my_temp.html", context)
  File "/Users/denisburguto/Library/Python/3.9/lib/python/site-packages/django/shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Users/denisburguto/Library/Python/3.9/lib/python/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/Users/denisburguto/Library/Python/3.9/lib/python/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: testapp3/my_temp.html
ERROR 2024-04-02 14:37:48,171 basehttp 20915 6164508672 "GET /three/my/den HTTP/1.1" 500 79128
WARNING 2024-04-02 14:37:49,310 log 20915 6164508672 Not Found: /three/my/
WARNING 2024-04-02 14:37:49,311 basehttp 20915 6164508672 "GET /three/my/ HTTP/1.1" 404 3617
ERROR 2024-04-02 14:37:57,167 log 20915 6164508672 Internal Server Error: /three/my/we
Traceback (most recent call last):
  File "/Users/denisburguto/Library/Python/3.9/lib/python/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/denisburguto/Library/Python/3.9/lib/python/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/denisburguto/test2django/test_project/testapp3/views.py", line 43, in my_view
    return render(request, "testapp3/my_temp.html", context)
  File "/Users/denisburguto/Library/Python/3.9/lib/python/site-packages/django/shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Users/denisburguto/Library/Python/3.9/lib/python/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/Users/denisburguto/Library/Python/3.9/lib/python/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: testapp3/my_temp.html
ERROR 2024-04-02 14:37:57,167 basehttp 20915 6164508672 "GET /three/my/we HTTP/1.1" 500 79111
INFO 2024-04-02 14:38:15,380 autoreload 20915 8444754624 /Users/denisburguto/test2django/test_project/testapp3/views.py changed, reloading.
INFO 2024-04-02 14:38:15,567 autoreload 20922 8444754624 Watching for file changes with StatReloader
ERROR 2024-04-02 14:38:19,087 log 20922 6135607296 Internal Server Error: /three/my/we
Traceback (most recent call last):
  File "/Users/denisburguto/Library/Python/3.9/lib/python/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/denisburguto/Library/Python/3.9/lib/python/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/denisburguto/test2django/test_project/testapp3/views.py", line 43, in my_view
    return render(request, "/testapp3/my_temp.html", context)
  File "/Users/denisburguto/Library/Python/3.9/lib/python/site-packages/django/shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Users/denisburguto/Library/Python/3.9/lib/python/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/Users/denisburguto/Library/Python/3.9/lib/python/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: /testapp3/my_temp.html
ERROR 2024-04-02 14:38:19,090 basehttp 20922 6135607296 "GET /three/my/we HTTP/1.1" 500 77954
INFO 2024-04-02 14:40:20,666 autoreload 20962 8444754624 Watching for file changes with StatReloader
ERROR 2024-04-02 14:40:24,615 log 20962 6132183040 Internal Server Error: /three/my/we
Traceback (most recent call last):
  File "/Users/denisburguto/Library/Python/3.9/lib/python/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/denisburguto/Library/Python/3.9/lib/python/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/denisburguto/test2django/test_project/testapp3/views.py", line 43, in my_view
    return render(request, "/testapp3/my_temp.html", context)
  File "/Users/denisburguto/Library/Python/3.9/lib/python/site-packages/django/shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Users/denisburguto/Library/Python/3.9/lib/python/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/Users/denisburguto/Library/Python/3.9/lib/python/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: /testapp3/my_temp.html
ERROR 2024-04-02 14:40:24,619 basehttp 20962 6132183040 "GET /three/my/we HTTP/1.1" 500 77954
ERROR 2024-04-02 14:40:33,331 log 20962 6132183040 Internal Server Error: /three/my/we
Traceback (most recent call last):
  File "/Users/denisburguto/Library/Python/3.9/lib/python/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/denisburguto/Library/Python/3.9/lib/python/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/denisburguto/test2django/test_project/testapp3/views.py", line 43, in my_view
    return render(request, "/testapp3/my_temp.html", context)
  File "/Users/denisburguto/Library/Python/3.9/lib/python/site-packages/django/shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Users/denisburguto/Library/Python/3.9/lib/python/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/Users/denisburguto/Library/Python/3.9/lib/python/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: /testapp3/my_temp.html
ERROR 2024-04-02 14:40:33,332 basehttp 20962 6132183040 "GET /three/my/we HTTP/1.1" 500 77954
INFO 2024-04-02 14:40:55,396 autoreload 20962 8444754624 /Users/denisburguto/test2django/test_project/testapp3/views.py changed, reloading.
INFO 2024-04-02 14:40:55,563 autoreload 20971 8444754624 Watching for file changes with StatReloader
INFO 2024-04-02 14:40:58,426 basehttp 20971 6171488256 "GET /three/my/we HTTP/1.1" 200 171
INFO 2024-04-02 14:41:03,152 basehttp 20971 6171488256 "GET /three/my/we HTTP/1.1" 200 171
INFO 2024-04-02 14:41:07,306 basehttp 20971 6171488256 "GET /three/my/Marina! HTTP/1.1" 200 176
INFO 2024-04-02 14:41:14,383 basehttp 20971 6171488256 "GET /three/my/we HTTP/1.1" 200 171
INFO 2024-04-02 14:41:19,769 basehttp 20971 6171488256 "GET /three/my/we HTTP/1.1" 200 171
INFO 2024-04-02 14:41:22,568 basehttp 20971 6171488256 "GET /three/my/we HTTP/1.1" 200 171
INFO 2024-04-02 14:41:27,175 basehttp 20971 6171488256 "GET /three/my/we HTTP/1.1" 200 171
INFO 2024-04-02 14:41:30,129 basehttp 20971 6171488256 "GET /three/my/we HTTP/1.1" 200 171
INFO 2024-04-02 14:41:33,464 basehttp 20971 6171488256 "GET /three/my/%D0%9C%D0%B0%D1%80%D0%B8%D0%BD%D0%B0 HTTP/1.1" 200 181
INFO 2024-04-02 15:20:33,994 basehttp 20971 6171488256 "GET /three/my/we HTTP/1.1" 200 171
INFO 2024-04-02 15:20:45,913 basehttp 20971 6171488256 "GET /three/my/%D0%AD%D0%BB%D1%8C%D0%B2%D0%B8%D1%80%D0%B0 HTTP/1.1" 200 183
INFO 2024-04-02 15:46:33,024 autoreload 20971 8444754624 /Users/denisburguto/test2django/test_project/testapp3/views.py changed, reloading.
INFO 2024-04-02 15:46:33,322 autoreload 21541 8444754624 Watching for file changes with StatReloader
INFO 2024-04-02 15:46:35,074 views 21541 6129954816 Index page accessed
INFO 2024-04-02 15:46:35,074 basehttp 21541 6129954816 "GET / HTTP/1.1" 200 13
INFO 2024-04-02 15:46:38,355 views 21541 6129954816 Index page accessed
INFO 2024-04-02 15:46:38,356 basehttp 21541 6129954816 "GET / HTTP/1.1" 200 13
INFO 2024-04-02 15:46:41,055 views 21541 6129954816 Index page accessed
INFO 2024-04-02 15:46:41,055 basehttp 21541 6129954816 "GET / HTTP/1.1" 200 13
INFO 2024-04-02 15:46:41,950 basehttp 21541 6129954816 "GET /three/my/we HTTP/1.1" 200 171
INFO 2024-04-02 15:46:46,328 basehttp 21541 6129954816 "GET /three HTTP/1.1" 301 0
INFO 2024-04-02 15:46:46,344 basehttp 21541 6129954816 "GET /three/ HTTP/1.1" 200 291
INFO 2024-04-02 15:55:23,853 autoreload 21541 8444754624 /Users/denisburguto/test2django/test_project/testapp3/urls.py changed, reloading.
INFO 2024-04-02 15:55:24,100 autoreload 21611 8444754624 Watching for file changes with StatReloader
INFO 2024-04-02 15:55:28,718 basehttp 21611 6202683392 "GET /three/for HTTP/1.1" 301 0
ERROR 2024-04-02 15:55:28,746 log 21611 6202683392 Internal Server Error: /three/for/
Traceback (most recent call last):
  File "/Users/denisburguto/Library/Python/3.9/lib/python/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/denisburguto/Library/Python/3.9/lib/python/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/denisburguto/test2django/test_project/testapp3/views.py", line 64, in view_for
    return render(request, 'myapp3/templ_for.html', context)
  File "/Users/denisburguto/Library/Python/3.9/lib/python/site-packages/django/shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Users/denisburguto/Library/Python/3.9/lib/python/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/Users/denisburguto/Library/Python/3.9/lib/python/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: myapp3/templ_for.html
ERROR 2024-04-02 15:55:28,749 basehttp 21611 6202683392 "GET /three/for/ HTTP/1.1" 500 81710
INFO 2024-04-02 15:56:16,067 autoreload 21611 8444754624 /Users/denisburguto/test2django/test_project/testapp3/views.py changed, reloading.
INFO 2024-04-02 15:56:16,233 autoreload 21635 8444754624 Watching for file changes with StatReloader
INFO 2024-04-02 15:56:20,257 basehttp 21635 6196637696 "GET /three/for/ HTTP/1.1" 200 955
INFO 2024-04-02 16:10:48,208 autoreload 21635 8444754624 /Users/denisburguto/test2django/test_project/testapp3/urls.py changed, reloading.
INFO 2024-04-02 16:10:48,465 autoreload 21770 8444754624 Watching for file changes with StatReloader
INFO 2024-04-02 16:10:50,099 views 21770 6164688896 Index page accessed
INFO 2024-04-02 16:10:50,099 basehttp 21770 6164688896 "GET / HTTP/1.1" 200 13
INFO 2024-04-02 16:10:53,183 views 21770 6164688896 Index page accessed
INFO 2024-04-02 16:10:53,184 basehttp 21770 6164688896 "GET / HTTP/1.1" 200 13
INFO 2024-04-02 16:10:56,859 basehttp 21770 6164688896 "GET /three/ HTTP/1.1" 200 291
INFO 2024-04-02 16:11:02,455 basehttp 21770 6164688896 "GET /three/index HTTP/1.1" 301 0
INFO 2024-04-02 16:11:02,475 basehttp 21770 6164688896 "GET /three/index/ HTTP/1.1" 200 180
INFO 2024-04-02 16:11:35,861 basehttp 21770 6164688896 "GET /three/about/ HTTP/1.1" 200 210
INFO 2024-04-02 16:12:11,210 basehttp 21770 6164688896 "GET /three/about/ HTTP/1.1" 200 210
INFO 2024-04-02 16:12:11,701 basehttp 21770 6164688896 "GET /three/ HTTP/1.1" 200 291
INFO 2024-04-02 16:12:12,478 basehttp 21770 6164688896 "GET /three/for/ HTTP/1.1" 200 955
INFO 2024-04-02 16:16:11,164 autoreload 21770 8444754624 /Users/denisburguto/test2django/test_project/test_project/settings.py changed, reloading.
INFO 2024-04-02 16:16:11,429 autoreload 21827 8444754624 Watching for file changes with StatReloader
INFO 2024-04-02 16:16:12,715 views 21827 6164361216 Index page accessed
INFO 2024-04-02 16:16:12,719 basehttp 21827 6164361216 "GET / HTTP/1.1" 200 13
INFO 2024-04-02 16:16:16,549 views 21827 6164361216 Index page accessed
INFO 2024-04-02 16:16:16,550 basehttp 21827 6164361216 "GET / HTTP/1.1" 200 13
INFO 2024-04-02 16:16:25,952 basehttp 21827 6164361216 "GET /three/ HTTP/1.1" 200 291
INFO 2024-04-02 16:16:26,820 basehttp 21827 6164361216 "GET /three/about/ HTTP/1.1" 200 210
INFO 2024-04-02 16:16:53,619 basehttp 21827 6164361216 "GET /three/about/ HTTP/1.1" 200 210
INFO 2024-04-02 16:16:54,345 basehttp 21827 6164361216 "GET /three/ HTTP/1.1" 200 291
INFO 2024-04-02 16:16:54,975 basehttp 21827 6164361216 "GET /three/index/ HTTP/1.1" 200 227
INFO 2024-04-02 16:19:18,826 autoreload 21827 8444754624 /Users/denisburguto/test2django/test_project/test_project/urls.py changed, reloading.
INFO 2024-04-02 16:19:19,096 autoreload 21865 8444754624 Watching for file changes with StatReloader
INFO 2024-04-02 16:19:20,613 basehttp 21865 6132232192 "GET / HTTP/1.1" 200 227
INFO 2024-04-02 16:20:07,050 autoreload 21865 8444754624 /Users/denisburguto/test2django/test_project/test_project/urls.py changed, reloading.
INFO 2024-04-02 16:20:07,236 autoreload 21872 8444754624 Watching for file changes with StatReloader
INFO 2024-04-02 16:20:19,450 autoreload 21872 8444754624 /Users/denisburguto/test2django/test_project/test_project/urls.py changed, reloading.
INFO 2024-04-02 16:20:19,635 autoreload 21883 8444754624 Watching for file changes with StatReloader
INFO 2024-04-02 16:30:07,224 autoreload 21883 8444754624 /Users/denisburguto/test2django/test_project/testapp3/models.py changed, reloading.
INFO 2024-04-02 16:30:07,522 autoreload 21976 8444754624 Watching for file changes with StatReloader
INFO 2024-04-02 16:43:16,038 autoreload 22952 8444754624 Watching for file changes with StatReloader
INFO 2024-04-02 16:58:29,057 autoreload 24598 8444754624 Watching for file changes with StatReloader
INFO 2024-04-02 16:58:56,624 autoreload 24663 8444754624 Watching for file changes with StatReloader
INFO 2024-04-02 16:59:00,025 basehttp 24663 6157856768 "GET / HTTP/1.1" 200 227
INFO 2024-04-02 17:04:57,457 autoreload 24663 8444754624 /Users/denisburguto/test2django/test_project/testapp3/views.py changed, reloading.
INFO 2024-04-02 17:04:57,723 autoreload 24720 8444754624 Watching for file changes with StatReloader
INFO 2024-04-02 17:12:02,034 autoreload 24720 8444754624 /Users/denisburguto/test2django/test_project/test_project/urls.py changed, reloading.
INFO 2024-04-02 17:12:02,294 autoreload 24794 8444754624 Watching for file changes with StatReloader
INFO 2024-04-02 17:12:24,699 basehttp 24794 6163017728 "GET / HTTP/1.1" 200 227
INFO 2024-04-02 17:12:28,771 basehttp 24794 6163017728 "GET / HTTP/1.1" 200 227
INFO 2024-04-02 17:12:30,294 basehttp 24794 6163017728 "GET /three/ HTTP/1.1" 200 291
INFO 2024-04-02 17:12:35,264 basehttp 24794 6163017728 "GET /three/ HTTP/1.1" 200 291
INFO 2024-04-02 17:12:37,007 basehttp 24794 6163017728 "GET /three/about/ HTTP/1.1" 200 210
INFO 2024-04-02 17:12:41,986 basehttp 24794 6163017728 "GET /three/author/2 HTTP/1.1" 301 0
INFO 2024-04-02 17:12:42,014 basehttp 24794 6163017728 "GET /three/author/2/ HTTP/1.1" 200 1082
INFO 2024-04-02 17:13:40,355 basehttp 24794 6163017728 "GET /three/author/2/ HTTP/1.1" 200 977
INFO 2024-04-02 17:13:45,687 basehttp 24794 6163017728 "GET /three/post/14/ HTTP/1.1" 200 640
INFO 2024-04-02 17:13:55,919 basehttp 24794 6163017728 "GET /three/post/11/ HTTP/1.1" 200 642
INFO 2024-04-02 17:17:12,096 basehttp 24794 6163017728 "GET /three/post/11/ HTTP/1.1" 200 642
WARNING 2024-04-02 17:17:21,083 log 24794 6163017728 Not Found: /three/post/50/
WARNING 2024-04-02 17:17:21,084 basehttp 24794 6163017728 "GET /three/post/50/ HTTP/1.1" 404 4646
INFO 2024-04-02 17:17:33,250 basehttp 24794 6163017728 "GET /three/post/4/ HTTP/1.1" 200 628
INFO 2024-04-02 17:17:42,837 basehttp 24794 6163017728 "GET /three/post/20/ HTTP/1.1" 200 646
INFO 2024-04-02 17:18:18,815 basehttp 24794 6163017728 "GET /three/post/22/ HTTP/1.1" 200 672
INFO 2024-04-07 09:04:17,449 autoreload 23300 8471935680 Watching for file changes with StatReloader
INFO 2024-04-07 09:04:59,131 autoreload 23384 8471935680 Watching for file changes with StatReloader
INFO 2024-04-07 09:05:03,015 basehttp 23384 6122844160 "GET / HTTP/1.1" 200 217
WARNING 2024-04-07 09:05:03,898 log 23384 6139670528 Not Found: /apple-touch-icon-precomposed.png
WARNING 2024-04-07 09:05:03,898 basehttp 23384 6139670528 "GET /apple-touch-icon-precomposed.png HTTP/1.1" 404 2592
WARNING 2024-04-07 09:05:03,910 log 23384 6139670528 Not Found: /apple-touch-icon.png
WARNING 2024-04-07 09:05:03,910 basehttp 23384 6139670528 "GET /apple-touch-icon.png HTTP/1.1" 404 2556
WARNING 2024-04-07 09:05:08,472 log 23384 6122844160 Not Found: /l4
WARNING 2024-04-07 09:05:08,473 basehttp 23384 6122844160 "GET /l4 HTTP/1.1" 404 2502
WARNING 2024-04-07 09:05:17,324 log 23384 6122844160 Not Found: /l4/
WARNING 2024-04-07 09:05:17,324 basehttp 23384 6122844160 "GET /l4/ HTTP/1.1" 404 2579
ERROR 2024-04-07 09:06:06,414 log 23384 6122844160 Internal Server Error: /l4/user/add/
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/django/core/handlers/base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/django/core/handlers/base.py", line 332, in check_response
    raise ValueError(
ValueError: The view testapp4.views.user_form didn't return an HttpResponse object. It returned None instead.
ERROR 2024-04-07 09:06:06,425 basehttp 23384 6122844160 "GET /l4/user/add/ HTTP/1.1" 500 65448
INFO 2024-04-07 09:13:06,490 autoreload 23384 8471935680 /Users/denisburguto/test2django/test_project/testapp4/views.py changed, reloading.
INFO 2024-04-07 09:13:06,834 autoreload 23666 8471935680 Watching for file changes with StatReloader
INFO 2024-04-07 09:13:08,145 basehttp 23666 6203699200 "GET / HTTP/1.1" 200 217
INFO 2024-04-07 09:13:13,867 basehttp 23666 6203699200 "GET / HTTP/1.1" 200 217
INFO 2024-04-07 09:13:56,368 basehttp 23666 6203699200 "GET / HTTP/1.1" 200 217
INFO 2024-04-07 09:13:59,759 basehttp 23666 6203699200 "GET / HTTP/1.1" 200 217
INFO 2024-04-07 09:14:13,630 basehttp 23666 6203699200 "GET / HTTP/1.1" 200 217
ERROR 2024-04-07 09:14:14,951 log 23666 6203699200 Internal Server Error: /l4/user/add/
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/denisburguto/test2django/test_project/testapp4/views.py", line 19, in user_form
    return render(request, 'myapp4/user_form.html', {'form': form})
                                                             ^^^^
UnboundLocalError: cannot access local variable 'form' where it is not associated with a value
ERROR 2024-04-07 09:14:14,952 basehttp 23666 6203699200 "GET /l4/user/add/ HTTP/1.1" 500 64243
ERROR 2024-04-07 09:14:15,881 log 23666 6203699200 Internal Server Error: /l4/user/add/
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/denisburguto/test2django/test_project/testapp4/views.py", line 19, in user_form
    return render(request, 'myapp4/user_form.html', {'form': form})
                                                             ^^^^
UnboundLocalError: cannot access local variable 'form' where it is not associated with a value
ERROR 2024-04-07 09:14:15,882 basehttp 23666 6203699200 "GET /l4/user/add/ HTTP/1.1" 500 64243
INFO 2024-04-07 09:15:00,719 autoreload 23666 8471935680 /Users/denisburguto/test2django/test_project/testapp4/views.py changed, reloading.
INFO 2024-04-07 09:15:00,988 autoreload 23719 8471935680 Watching for file changes with StatReloader
INFO 2024-04-07 09:15:02,136 basehttp 23719 6171373568 "GET / HTTP/1.1" 200 217
INFO 2024-04-07 09:15:05,186 basehttp 23719 6171373568 "GET / HTTP/1.1" 200 217
ERROR 2024-04-07 09:15:08,343 log 23719 6171373568 Internal Server Error: /l4/user/add/
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/denisburguto/test2django/test_project/testapp4/views.py", line 19, in user_form
    return render(request, 'myapp4/user_form.html', {'form': form})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: myapp4/user_form.html
ERROR 2024-04-07 09:15:08,345 basehttp 23719 6171373568 "GET /l4/user/add/ HTTP/1.1" 500 80131
INFO 2024-04-07 09:15:41,856 autoreload 23719 8471935680 /Users/denisburguto/test2django/test_project/testapp4/views.py changed, reloading.
INFO 2024-04-07 09:15:42,123 autoreload 23743 8471935680 Watching for file changes with StatReloader
INFO 2024-04-07 09:15:45,680 basehttp 23743 6134575104 "GET /l4/user/add/ HTTP/1.1" 200 541
INFO 2024-04-07 09:29:22,739 basehttp 23743 6134575104 "GET / HTTP/1.1" 200 217
INFO 2024-04-07 09:29:26,032 basehttp 23743 6134575104 "GET / HTTP/1.1" 200 217
INFO 2024-04-07 09:29:32,033 basehttp 23743 6134575104 "GET /l4/user/add/ HTTP/1.1" 200 763
INFO 2024-04-07 09:29:40,460 basehttp 23743 6134575104 "POST /l4/user/add/ HTTP/1.1" 200 813
INFO 2024-04-07 09:29:41,761 basehttp 23743 6134575104 "POST /l4/user/add/ HTTP/1.1" 200 813
INFO 2024-04-07 09:30:29,402 basehttp 23743 6134575104 "POST /l4/user/add/ HTTP/1.1" 200 813
INFO 2024-04-07 09:30:29,907 basehttp 23743 6134575104 "POST /l4/user/add/ HTTP/1.1" 200 813
INFO 2024-04-07 09:30:30,061 basehttp 23743 6134575104 "POST /l4/user/add/ HTTP/1.1" 200 813
INFO 2024-04-07 09:30:30,196 basehttp 23743 6134575104 "POST /l4/user/add/ HTTP/1.1" 200 813
INFO 2024-04-07 09:30:30,312 basehttp 23743 6134575104 "POST /l4/user/add/ HTTP/1.1" 200 813
INFO 2024-04-07 09:30:32,918 basehttp 23743 6134575104 "POST /l4/user/add/ HTTP/1.1" 200 817
INFO 2024-04-07 09:30:33,254 basehttp 23743 6134575104 "POST /l4/user/add/ HTTP/1.1" 200 817
INFO 2024-04-07 09:30:33,389 basehttp 23743 6134575104 "POST /l4/user/add/ HTTP/1.1" 200 817
INFO 2024-04-07 09:30:39,792 basehttp 23743 6134575104 "POST /l4/user/add/ HTTP/1.1" 200 817
INFO 2024-04-07 09:31:20,965 autoreload 23743 8471935680 /Users/denisburguto/test2django/test_project/testapp4/views.py changed, reloading.
INFO 2024-04-07 09:31:21,264 autoreload 24193 8471935680 Watching for file changes with StatReloader
INFO 2024-04-07 09:31:26,394 basehttp 24193 6157578240 "POST /l4/user/add/ HTTP/1.1" 200 817
INFO 2024-04-07 09:32:07,984 autoreload 24193 8471935680 /Users/denisburguto/test2django/test_project/test_project/settings.py changed, reloading.
INFO 2024-04-07 09:32:08,280 autoreload 24218 8471935680 Watching for file changes with StatReloader
INFO 2024-04-07 09:32:11,460 views 24218 6203830272 Получили name='ыва', email='vel6545158@yandex.ru', age=1.
INFO 2024-04-07 09:32:11,476 basehttp 24218 6203830272 "POST /l4/user/add/ HTTP/1.1" 200 817
INFO 2024-04-07 09:46:36,933 autoreload 24218 8471935680 /Users/denisburguto/test2django/test_project/testapp4/forms.py changed, reloading.
INFO 2024-04-07 09:46:37,274 autoreload 24537 8471935680 Watching for file changes with StatReloader
INFO 2024-04-07 09:59:38,746 autoreload 24537 8471935680 /Users/denisburguto/test2django/test_project/testapp4/forms.py changed, reloading.
INFO 2024-04-07 09:59:39,083 autoreload 24873 8471935680 Watching for file changes with StatReloader
INFO 2024-04-07 09:59:59,435 autoreload 24873 8471935680 /Users/denisburguto/test2django/test_project/testapp4/forms.py changed, reloading.
INFO 2024-04-07 09:59:59,842 autoreload 24896 8471935680 Watching for file changes with StatReloader
INFO 2024-04-07 10:14:38,572 autoreload 24896 8471935680 /Users/denisburguto/test2django/test_project/testapp4/urls.py changed, reloading.
INFO 2024-04-07 10:14:38,860 autoreload 25239 8471935680 Watching for file changes with StatReloader
INFO 2024-04-07 10:16:13,352 autoreload 25239 8471935680 /Users/denisburguto/test2django/test_project/testapp4/views.py changed, reloading.
INFO 2024-04-07 10:16:13,687 autoreload 25295 8471935680 Watching for file changes with StatReloader
INFO 2024-04-07 10:17:52,920 basehttp 25295 6122385408 "GET / HTTP/1.1" 200 217
INFO 2024-04-07 10:17:56,104 basehttp 25295 6122385408 "GET / HTTP/1.1" 200 217
WARNING 2024-04-07 10:17:58,115 log 25295 6122385408 Not Found: /form
WARNING 2024-04-07 10:17:58,115 basehttp 25295 6122385408 "GET /form HTTP/1.1" 404 2508
WARNING 2024-04-07 10:18:03,479 log 25295 6122385408 Not Found: /fake_users/25
WARNING 2024-04-07 10:18:03,480 basehttp 25295 6122385408 "GET /fake_users/25 HTTP/1.1" 404 2535
INFO 2024-04-07 10:18:03,859 basehttp 25295 6122385408 "GET / HTTP/1.1" 200 217
INFO 2024-04-07 10:18:04,625 basehttp 25295 6122385408 "GET /l4/user/add/ HTTP/1.1" 200 763
WARNING 2024-04-07 10:18:07,273 log 25295 6122385408 Not Found: /l4.form
WARNING 2024-04-07 10:18:07,273 basehttp 25295 6122385408 "GET /l4.form HTTP/1.1" 404 2517
WARNING 2024-04-07 10:18:10,344 log 25295 6122385408 Not Found: /l4.form
WARNING 2024-04-07 10:18:10,344 basehttp 25295 6122385408 "GET /l4.form HTTP/1.1" 404 2517
INFO 2024-04-07 10:18:14,881 basehttp 25295 6122385408 "GET /l4/user/add/ HTTP/1.1" 200 763
INFO 2024-04-07 10:18:16,524 basehttp 25295 6122385408 "GET /l4/user/add/ HTTP/1.1" 200 763
INFO 2024-04-07 10:18:19,272 basehttp 25295 6122385408 "GET /l4/form HTTP/1.1" 301 0
ERROR 2024-04-07 10:18:19,313 log 25295 6122385408 Internal Server Error: /l4/form/
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/denisburguto/test2django/test_project/testapp4/views.py", line 30, in many_fields_form
    return render(request, 'testapp4/many_fields_form.html',
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: testapp4/many_fields_form.html
ERROR 2024-04-07 10:18:19,314 basehttp 25295 6122385408 "GET /l4/form/ HTTP/1.1" 500 80384
INFO 2024-04-07 10:18:38,172 autoreload 25295 8471935680 /Users/denisburguto/test2django/test_project/testapp4/views.py changed, reloading.
INFO 2024-04-07 10:18:38,485 autoreload 25358 8471935680 Watching for file changes with StatReloader
INFO 2024-04-07 10:18:40,471 basehttp 25358 6159560704 "GET /l4/form/ HTTP/1.1" 200 1257
INFO 2024-04-07 10:20:20,540 views 25358 6159560704 Получили form.cleaned_data={'name': 'dsf', 'email': 'vel6545158@yandex.ru', 'age': 33, 'height': 3.3, 'is_active': True, 'birthdate': datetime.date(2024, 4, 7)}.
INFO 2024-04-07 10:20:20,547 basehttp 25358 6159560704 "POST /l4/form/ HTTP/1.1" 200 1329
INFO 2024-04-07 10:20:41,320 views 25358 6159560704 Получили form.cleaned_data={'name': 'dsf', 'email': 'vel6545158@yandex.ru', 'age': 33, 'height': 3.3, 'is_active': True, 'birthdate': datetime.date(2024, 4, 7)}.
INFO 2024-04-07 10:20:41,324 basehttp 25358 6159560704 "POST /l4/form/ HTTP/1.1" 200 1329
INFO 2024-04-07 10:31:52,871 autoreload 25358 8471935680 /Users/denisburguto/test2django/test_project/testapp4/views.py changed, reloading.
INFO 2024-04-07 10:31:53,247 autoreload 25765 8471935680 Watching for file changes with StatReloader
INFO 2024-04-07 10:33:16,318 autoreload 25765 8471935680 /Users/denisburguto/test2django/test_project/testapp4/forms.py changed, reloading.
INFO 2024-04-07 10:33:16,638 autoreload 25834 8471935680 Watching for file changes with StatReloader
INFO 2024-04-07 10:41:56,148 autoreload 25834 8471935680 /Users/denisburguto/test2django/test_project/testapp4/views.py changed, reloading.
INFO 2024-04-07 10:41:56,448 autoreload 26045 8471935680 Watching for file changes with StatReloader
INFO 2024-04-07 10:41:57,762 basehttp 26045 6200406016 "GET / HTTP/1.1" 200 217
INFO 2024-04-07 10:42:01,062 basehttp 26045 6200406016 "GET / HTTP/1.1" 200 217
WARNING 2024-04-07 10:42:02,395 log 26045 6200406016 Not Found: /fake_users/25
WARNING 2024-04-07 10:42:02,395 basehttp 26045 6200406016 "GET /fake_users/25 HTTP/1.1" 404 2535
INFO 2024-04-07 10:42:03,439 basehttp 26045 6200406016 "GET / HTTP/1.1" 200 217
INFO 2024-04-07 10:42:04,370 basehttp 26045 6200406016 "GET /l4/user/add/ HTTP/1.1" 200 763
INFO 2024-04-07 10:42:08,060 basehttp 26045 6200406016 "GET /l4/form/ HTTP/1.1" 200 2072
INFO 2024-04-07 10:42:48,794 basehttp 26045 6200406016 "GET /l4/form/ HTTP/1.1" 200 2072
INFO 2024-04-07 10:45:11,777 autoreload 26045 8471935680 /Users/denisburguto/test2django/test_project/testapp4/forms.py changed, reloading.
INFO 2024-04-07 10:45:12,041 autoreload 26144 8471935680 Watching for file changes with StatReloader
INFO 2024-04-07 10:45:15,870 basehttp 26144 6161182720 "GET /l4/form/ HTTP/1.1" 200 2072
INFO 2024-04-07 10:55:39,046 autoreload 26144 8471935680 /Users/denisburguto/test2django/test_project/testapp4/forms.py changed, reloading.
INFO 2024-04-07 10:55:39,396 autoreload 26406 8471935680 Watching for file changes with StatReloader
INFO 2024-04-07 10:55:49,562 autoreload 26406 8471935680 /Users/denisburguto/test2django/test_project/testapp4/forms.py changed, reloading.
INFO 2024-04-07 10:55:49,858 autoreload 26418 8471935680 Watching for file changes with StatReloader
INFO 2024-04-07 10:56:37,403 autoreload 26418 8471935680 /Users/denisburguto/test2django/test_project/testapp4/forms.py changed, reloading.
INFO 2024-04-07 10:56:37,695 autoreload 26465 8471935680 Watching for file changes with StatReloader
INFO 2024-04-07 11:02:51,139 autoreload 26465 8471935680 /Users/denisburguto/test2django/test_project/testapp4/models.py changed, reloading.
INFO 2024-04-07 11:02:51,563 autoreload 26632 8471935680 Watching for file changes with StatReloader
INFO 2024-04-07 11:37:43,827 autoreload 27204 8471935680 Watching for file changes with StatReloader
INFO 2024-04-07 11:37:45,499 basehttp 27204 6165098496 "GET / HTTP/1.1" 200 217
INFO 2024-04-07 11:37:49,880 basehttp 27204 6165098496 "GET / HTTP/1.1" 200 217
INFO 2024-04-07 11:37:53,297 basehttp 27204 6165098496 "GET / HTTP/1.1" 200 217
INFO 2024-04-07 11:37:54,185 basehttp 27204 6165098496 "GET /l4/user/add/ HTTP/1.1" 200 763
INFO 2024-04-07 11:38:06,780 basehttp 27204 6165098496 "GET /l4/user/add/ HTTP/1.1" 200 763
INFO 2024-04-07 11:38:07,431 basehttp 27204 6165098496 "GET /l4/user/ HTTP/1.1" 200 763
INFO 2024-04-07 11:38:11,607 basehttp 27204 6165098496 "GET /l4/user/ HTTP/1.1" 200 763
INFO 2024-04-07 11:38:12,190 basehttp 27204 6165098496 "GET /l4/user HTTP/1.1" 301 0
INFO 2024-04-07 11:38:12,210 basehttp 27204 6165098496 "GET /l4/user/ HTTP/1.1" 200 763
INFO 2024-04-07 11:38:29,473 basehttp 27204 6165098496 "POST /l4/user/ HTTP/1.1" 200 922
INFO 2024-04-07 11:38:48,446 basehttp 27204 6165098496 "POST /l4/user/ HTTP/1.1" 200 918
INFO 2024-04-07 11:39:33,035 basehttp 27204 6165098496 "POST /l4/user/ HTTP/1.1" 200 918
INFO 2024-04-07 11:39:33,246 basehttp 27204 6165098496 "POST /l4/user/ HTTP/1.1" 200 918
INFO 2024-04-07 11:39:33,423 basehttp 27204 6165098496 "POST /l4/user/ HTTP/1.1" 200 918
INFO 2024-04-07 11:39:33,557 basehttp 27204 6165098496 "POST /l4/user/ HTTP/1.1" 200 918
INFO 2024-04-07 11:40:19,134 basehttp 27204 6165098496 "POST /l4/user/ HTTP/1.1" 200 918
INFO 2024-04-07 11:40:19,367 basehttp 27204 6165098496 "POST /l4/user/ HTTP/1.1" 200 918
INFO 2024-04-07 11:41:20,888 views 27204 6165098496 Получили name='test', email='vel6545158@vk.team', age=7.
INFO 2024-04-07 11:41:20,902 basehttp 27204 6165098496 "POST /l4/user/ HTTP/1.1" 200 813
INFO 2024-04-07 11:43:55,583 views 27204 6165098496 Получили name='test2', email='vel6545158@vk.team', age=7.
ERROR 2024-04-07 11:44:00,770 log 27204 6165098496 Internal Server Error: /l4/user/
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/django/db/utils.py", line 98, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: database is locked

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/denisburguto/test2django/test_project/testapp4/views.py", line 45, in add_user
    user.save()
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/django/db/models/base.py", line 822, in save
    self.save_base(
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/django/db/models/base.py", line 909, in save_base
    updated = self._save_table(
              ^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/django/db/models/base.py", line 1067, in _save_table
    results = self._do_insert(
              ^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/django/db/models/base.py", line 1108, in _do_insert
    return manager._insert(
           ^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/django/db/models/query.py", line 1847, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/django/db/models/sql/compiler.py", line 1835, in execute_sql
    self.connection.ops.fetch_returned_insert_columns(
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/django/db/backends/base/operations.py", line 216, in fetch_returned_insert_columns
    return cursor.fetchone()
           ^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/django/db/utils.py", line 97, in inner
    with self:
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/django/db/utils.py", line 98, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
django.db.utils.OperationalError: database is locked
ERROR 2024-04-07 11:44:00,775 basehttp 27204 6165098496 "POST /l4/user/ HTTP/1.1" 500 124234
INFO 2024-04-07 11:44:24,688 views 27204 6165098496 Получили name='test2', email='vel6545158@vk.team', age=7.
INFO 2024-04-07 11:44:24,703 basehttp 27204 6165098496 "POST /l4/user/ HTTP/1.1" 200 867
INFO 2024-04-07 11:45:33,446 basehttp 27204 6165098496 "GET /l4/user/ HTTP/1.1" 200 802
INFO 2024-04-07 11:52:35,069 autoreload 27204 8471935680 /Users/denisburguto/test2django/test_project/test_project/settings.py changed, reloading.
INFO 2024-04-07 11:52:35,398 autoreload 27681 8471935680 Watching for file changes with StatReloader
INFO 2024-04-07 11:54:00,888 autoreload 27681 8471935680 /Users/denisburguto/test2django/test_project/testapp4/forms.py changed, reloading.
INFO 2024-04-07 11:54:01,243 autoreload 27715 8471935680 Watching for file changes with StatReloader
INFO 2024-04-07 11:54:22,669 autoreload 27715 8471935680 /Users/denisburguto/test2django/test_project/testapp4/forms.py changed, reloading.
INFO 2024-04-07 11:54:22,980 autoreload 27733 8471935680 Watching for file changes with StatReloader
INFO 2024-04-07 11:55:11,746 autoreload 27733 8471935680 /Users/denisburguto/test2django/test_project/testapp4/views.py changed, reloading.
INFO 2024-04-07 11:55:12,069 autoreload 27759 8471935680 Watching for file changes with StatReloader
INFO 2024-04-07 11:58:09,938 autoreload 27759 8471935680 /Users/denisburguto/test2django/test_project/testapp4/urls.py changed, reloading.
INFO 2024-04-07 11:58:10,349 autoreload 27844 8471935680 Watching for file changes with StatReloader
INFO 2024-04-07 11:58:45,940 autoreload 27844 8471935680 /Users/denisburguto/test2django/test_project/testapp4/views.py changed, reloading.
INFO 2024-04-07 11:58:46,364 autoreload 27877 8471935680 Watching for file changes with StatReloader
INFO 2024-04-07 12:00:23,487 basehttp 27877 6189363200 "GET / HTTP/1.1" 200 217
INFO 2024-04-07 12:00:26,919 basehttp 27877 6189363200 "GET / HTTP/1.1" 200 217
INFO 2024-04-07 12:00:29,440 basehttp 27877 6189363200 "GET /l4/user/add/ HTTP/1.1" 200 773
INFO 2024-04-07 12:00:34,998 basehttp 27877 6189363200 "GET /l4/upload HTTP/1.1" 301 0
INFO 2024-04-07 12:00:35,019 basehttp 27877 6189363200 "GET /l4/upload/ HTTP/1.1" 200 574
INFO 2024-04-07 12:00:42,851 basehttp 27877 6189363200 "POST /l4/upload/ HTTP/1.1" 200 574
